[package]
name = "circular_buffer"
version = "0.1.0"
authors = ["pk1890 <piotrekkotara@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
cargo-valgrind = "1.3.0"